# -*- coding: utf-8 -*-
"""generate_kpi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18gjUxp8nmR7vOsUpDNQpsQu-YtNgS7_R
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler

INPUT_FILE = "/content/university_final_dataset.xlsx"

df = pd.read_excel(INPUT_FILE)

print("Dataset Loaded Successfully")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

numeric_cols = [
    'overall_score',
    'academic_reputation_score',
    'citations_per_faculty_score',
    'faculty_student_score',
    'international_students_score',
    'research_score',
    'citation_score'
]

for col in numeric_cols:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors='coerce')

# =====================================
# KPI 1 : GLOBAL RANKING SCORE
# =====================================

if 'overall_score' in df.columns:
    df['global_ranking_score'] = df['overall_score']

# =====================================
# KPI 2 : RESEARCH IMPACT SCORE
# =====================================

if 'citations_per_faculty_score' in df.columns:
    df['research_impact_score'] = df['citations_per_faculty_score']

elif 'citation_score' in df.columns:
    df['research_impact_score'] = df['citation_score']

# =====================================
# KPI 3 : FACULTY TO STUDENT RATIO
# =====================================

if 'students_per_staff' in df.columns:
    df['faculty_student_ratio'] = (
        1 / df['students_per_staff']
    )

elif 'faculty_student_score' in df.columns:
    df['faculty_student_ratio'] = df['faculty_student_score']

# =====================================
# KPI 4 : INTERNATIONAL STUDENT %
# =====================================

if 'international_student_percentage' in df.columns:
    df['international_student_percentage_kpi'] = (
        df['international_student_percentage']
    )

elif 'international_students_score' in df.columns:
    df['international_student_percentage_kpi'] = (
        df['international_students_score']
    )

# =====================================
# KPI 5 : ACADEMIC REPUTATION SCORE
# =====================================

if 'academic_reputation_score' in df.columns:
    df['academic_reputation_kpi'] = (
        df['academic_reputation_score']
    )

# =====================================
# KPI 6 : RESEARCH PRODUCTIVITY INDEX
# =====================================

research_cols = []

if 'research_score' in df.columns:
    research_cols.append('research_score')

if 'citation_score' in df.columns:
    research_cols.append('citation_score')

if 'research_impact_score' in df.columns:
    research_cols.append('research_impact_score')

if len(research_cols) >= 2:

    scaler = MinMaxScaler()

    df[research_cols] = scaler.fit_transform(
        df[research_cols].fillna(0)
    )

    if len(research_cols) == 3:

        df['research_productivity_index'] = (
            0.50 * df['research_score']
            + 0.30 * df['citation_score']
            + 0.20 * df['research_impact_score']
        )

    else:

        df['research_productivity_index'] = (
            df[research_cols].mean(axis=1)
        )

if 'university_id' not in df.columns:

    df['university_id'] = [
        f"U{str(i).zfill(4)}"
        for i in range(1, len(df) + 1)
    ]

final_columns = [
    'university_id'
]

possible_cols = [
    'institution_name',
    'university_name',
    'location',
    'country',
    'global_ranking_score',
    'research_impact_score',
    'faculty_student_ratio',
    'international_student_percentage_kpi',
    'academic_reputation_kpi',
    'research_productivity_index'
]

for col in possible_cols:
    if col in df.columns:
        final_columns.append(col)

final_df = df[final_columns]

OUTPUT_FILE = "eduvision_final_dataset.xlsx"

final_df.to_excel(
    OUTPUT_FILE,
    index=False
)

print("\nKPI Generation Complete")
print("Output File:", OUTPUT_FILE)
print("Rows Exported:", final_df.shape[0])

print("\n===== KPI SUMMARY =====")

kpi_cols = [
    'global_ranking_score',
    'research_impact_score',
    'faculty_student_ratio',
    'international_student_percentage_kpi',
    'academic_reputation_kpi',
    'research_productivity_index'
]

for col in kpi_cols:

    if col in final_df.columns:

        print(f"\n{col}")

        print(
            final_df[col]
            .describe()
        )