import os

doc_dir = r"c:\Users\mbpsi\OneDrive\Desktop\EduVision_DV\documentation"
os.makedirs(doc_dir, exist_ok=True)

md = []
md.append("# EduVision_DV – Tableau Data Source & Integration Guide\n")
md.append("## Executive Summary\n")
md.append("This document serves as the authoritative guide for connecting the **EduVision_DV** final analytical data package into Tableau Desktop / Tableau Cloud / Tableau Server. The data model is designed using Tableau's native **Logical Layer Relationships** (Noodles) to preserve table granularities, prevent accidental Cartesian joins, and eliminate data duplication.\n")

md.append("--- \n")
md.append("## 1. Final Data Package Structure (`../../data/final/`)\n")
md.append("The final Tableau data package consists of seven curated CSV files:\n\n")

md.append("| File Name | Role in Tableau | Primary Key (PK) | Foreign Key(s) | Granularity Level |")
md.append("| --- | --- | --- | --- | --- |")
md.append("| `dim_university.csv` | University Dimension | `university_id` | `country_id` | 1 row per unique university entity |")
md.append("| `dim_country.csv` | Country Dimension | `country_id` | N/A | 1 row per unique canonical country |")
md.append("| `fact_university_performance.csv` | Institutional Rank Fact | (`university_id`, `year`, `source_ranking`) | `university_id` | 1 row per university per year per ranking source |")
md.append("| `fact_research.csv` | Research Analytics Fact | (`university_id`, `year`, `source_ranking`) | `university_id` | 1 row per university per year per ranking source |")
md.append("| `fact_student.csv` | Student Analytics Fact | (`university_id`, `year`, `source_ranking`) | `university_id` | 1 row per university per year per ranking source |")
md.append("| `fact_country_education.csv` | Macro Country Fact | (`country_id`, `year`, `indicator_code`) | `country_id` | 1 row per country per year per indicator |")
md.append("| `kpi_university.csv` | Consolidated KPI Table | `university_id` | `country_id` | 1 row per university summary KPI profile |")

md.append("\n---\n")
md.append("## 2. Recommended Tableau Data Model Architecture\n")
md.append("To support the four required Tableau dashboards (**University Overview**, **Research Analytics**, **Student Analytics**, and **Country Comparison**), use Tableau's Logical Data Model with two clean star schemas.\n\n")

md.append("### Schema 1: Higher Education Institutional Performance Model\n")
md.append("Used for **University Overview**, **Research Analytics**, and **Student Analytics** dashboards.\n\n")
md.append("```\n")
md.append("                           +-----------------------+\n")
md.append("                           |      dim_country      |\n")
md.append("                           +-----------------------+\n")
md.append("                           | PK: country_id        |\n")
md.append("                           +-----------+-----------+\n")
md.append("                                       |\n")
md.append("                                       | 1:N (Relationship on country_id)\n")
md.append("                                       v\n")
md.append("                           +-----------------------+\n")
md.append("                           |    dim_university     |\n")
md.append("                           +-----------------------+\n")
md.append("                           | PK: university_id     |\n")
md.append("                           | FK: country_id        |\n")
md.append("                           +-----------+-----------+\n")
md.append("                                       |\n")
md.append("        +------------------------------+------------------------------+\n")
md.append("        | 1:N                          | 1:N                          | 1:N\n")
md.append("        v                              v                              v\n")
md.append("+-----------------------+      +-----------------------+      +-----------------------+\n")
md.append("| fact_university_perf  |      |     fact_research     |      |     fact_student      |\n")
md.append("+-----------------------+      +-----------------------+      +-----------------------+\n")
md.append("| FK: university_id     |      | FK: university_id     |      | FK: university_id     |\n")
md.append("| year, global_rank     |      | year, research_score  |      | year, total_students  |\n")
md.append("| overall_score         |      | citation_score        |      | students_per_staff    |\n")
md.append("+-----------------------+      +-----------------------+      +-----------------------+\n")
md.append("```\n\n")

md.append("### Schema 2: Country Macro-Level Education Model\n")
md.append("Used for the **Country Comparison** dashboard to analyze macro-level World Bank statistics alongside national aggregate university performance.\n\n")
md.append("```\n")
md.append("                           +-----------------------+\n")
md.append("                           |      dim_country      |\n")
md.append("                           +-----------------------+\n")
md.append("                           | PK: country_id        |\n")
md.append("                           +-----------+-----------+\n")
md.append("                                       |\n")
md.append("                                       | 1:N (Relationship on country_id)\n")
md.append("                                       v\n")
md.append("                           +-----------------------+\n")
md.append("                           |fact_country_education |\n")
md.append("                           +-----------------------+\n")
md.append("                           | FK: country_id        |\n")
md.append("                           | year, indicator, value|\n")
md.append("                           +-----------------------+\n")
md.append("```\n\n")

md.append("---\n")
md.append("## 3. Detailed Tableau Relationship Configurations\n\n")

md.append("### Connection 1: `dim_university` to `dim_country`\n")
md.append("- **Left Table**: `dim_university.csv`\n")
md.append("- **Right Table**: `dim_country.csv`\n")
md.append("- **Relationship Clause**: `dim_university.country_id = dim_country.country_id`\n")
md.append("- **Cardinality**: Many-to-One (Many universities per 1 country)\n")
md.append("- **Performance Option**: Referencing Integrity = `Some Records Match`\n\n")

md.append("### Connection 2: `dim_university` to `fact_university_performance`\n")
md.append("- **Left Table**: `dim_university.csv`\n")
md.append("- **Right Table**: `fact_university_performance.csv`\n")
md.append("- **Relationship Clause**: `dim_university.university_id = fact_university_performance.university_id`\n")
md.append("- **Cardinality**: One-to-Many (1 university has multiple annual ranking records across QS/THE)\n")
md.append("- **Performance Option**: Cardinality = `One-to-Many`\n\n")

md.append("### Connection 3: `dim_university` to `fact_research`\n")
md.append("- **Left Table**: `dim_university.csv`\n")
md.append("- **Right Table**: `fact_research.csv`\n")
md.append("- **Relationship Clause**: `dim_university.university_id = fact_research.university_id`\n")
md.append("- **Cardinality**: One-to-Many\n\n")

md.append("### Connection 4: `dim_university` to `fact_student`\n")
md.append("- **Left Table**: `dim_university.csv`\n")
md.append("- **Right Table**: `fact_student.csv`\n")
md.append("- **Relationship Clause**: `dim_university.university_id = fact_student.university_id`\n")
md.append("- **Cardinality**: One-to-Many\n\n")

md.append("### Connection 5: `dim_country` to `fact_country_education`\n")
md.append("- **Left Table**: `dim_country.csv`\n")
md.append("- **Right Table**: `fact_country_education.csv`\n")
md.append("- **Relationship Clause**: `dim_country.country_id = fact_country_education.country_id`\n")
md.append("- **Cardinality**: One-to-Many (1 country has multiple annual indicator records)\n\n")

md.append("---\n")
md.append("## 4. Dashboard Field & Filter Mapping Guide\n\n")

md.append("### Dashboard 1: University Overview Dashboard\n")
md.append("- **Primary Data Source**: Schema 1 (`dim_university` + `fact_university_performance` + `kpi_university`)\n")
md.append("- **Key Metrics**: `global_ranking_score`, `global_rank`, `overall_score`, `academic_reputation`\n")
md.append("- **Recommended Tableau Filters**:\n")
md.append("  - `source_ranking` (Single Value Dropdown e.g., *QS World University Rankings 2025*)\n")
md.append("  - `region` (Multiple Values List)\n")
md.append("  - `country_name` (Single Value Dropdown with Search)\n")
md.append("  - `global_rank` (Range Slider e.g., Top 100, Top 500)\n\n")

md.append("### Dashboard 2: Research Analytics Dashboard\n")
md.append("- **Primary Data Source**: Schema 1 (`dim_university` + `fact_research` + `kpi_university`)\n")
md.append("- **Key Metrics**: `research_impact_score`, `research_productivity_index`, `citation_score`, `citations_per_faculty_score`, `international_research_network_score`\n")
md.append("- **Recommended Tableau Filters**:\n")
md.append("  - `source_ranking`\n")
md.append("  - `region`\n")
md.append("  - `research_productivity_index` (Range Slider)\n\n")

md.append("### Dashboard 3: Student Analytics Dashboard\n")
md.append("- **Primary Data Source**: Schema 1 (`dim_university` + `fact_student` + `kpi_university`)\n")
md.append("- **Key Metrics**: `faculty_student_ratio`, `international_student_percentage`, `total_students`, `students_per_staff`, `female_male_ratio`\n")
md.append("- **Recommended Tableau Filters**:\n")
md.append("  - `source_ranking`\n")
md.append("  - `region`\n")
md.append("  - `international_student_percentage` (Range Slider)\n\n")

md.append("### Dashboard 4: Country Comparison Dashboard\n")
md.append("- **Primary Data Source**: Schema 2 (`dim_country` + `fact_country_education` + `fact_university_performance`)\n")
md.append("- **Key Metrics**: `ranked_university_count`, `avg_global_ranking_score`, `indicator_name` / `value` (World Bank Tertiary Enrolment %, Education Expenditure % GDP)\n")
md.append("- **Recommended Tableau Filters**:\n")
md.append("  - `region`\n")
md.append("  - `year` (Multi-year timeline slider e.g., 2000–2017)\n")
md.append("  - `indicator` (Parameter Control / Dropdown)\n\n")

md.append("---\n")
md.append("## 5. Important Tableau Best Practices & Tips\n")
md.append("1. **Use Logical Relationships over Physical Joins**: Do not merge files physically into one flat table in Tableau Data Source tab. Use Tableau Noodles (relationships) to keep queries fast and aggregations accurate.\n")
md.append("2. **Null Values**: Do not convert nulls to 0 in Tableau calculations. Use `IFNULL()` or `ZN()` only when creating specific display labels.\n")
md.append("3. **Filter Context**: When calculating Top N universities, add `region` or `country_name` filters to Context in Tableau (`Add to Context`).\n")

doc_path = os.path.join(doc_dir, "tableau_data_source_guide.md")
with open(doc_path, "w", encoding="utf-8") as f:
    f.write("\n".join(md))

print(f"Exported {doc_path}")
